### ISSUE TITLE
SynchronousFuture instead of Future.value in messages_all.dart

### ISSUE THREAD

**Issue by michelerenzullo** [localizely/intl_utils#100]
I was using 2.8.0 and everything ok, but after commit [#93198e6](https://github.com/localizely/intl_utils/commit/93198e60b183c108cc46b6bee4502e1853010927#) merged in v2.8.1 a couple of tests in our app are broken, this seems to be caused by the implementation of `SynchronousFuture` over the previous `Future.value` in `messages_all.dart`, note we have `use_deferred_loading: false` as default, I know that has been implemented to fix black frames, but in order to make it work v2.8.1 I have to `sed -i '' 's/SynchronousFuture/Future.value/g' messages_all.dart` , what might be wrong in my test or in your plugin? Thanks in advance

I decided to stay on 2.8.0 at moment.

**Comment by AndrewBert** [comment]
Same here. Any updates?

**Comment by michelerenzullo** [comment]
Nope from my side

**Comment by michelerenzullo** [comment]
Updates?

**Comment by AndrewBert** [comment]
We just had to adjust how we initialized our blocs in our tests. Essentially, rather than creating an initial event to set the initial state, we just passed the initial state directly to the constructor. And this fixed our issues with the new timing.

**Comment by AndrewBert** [comment]
> Updates?

We just had to adjust how we initialized our blocs in our tests. Essentially, rather than creating an initial event to set the initial state, we just passed the initial state directly to the constructor. And this fixed our issues with the new timing.

**Comment by michelerenzullo** [comment]
Thanks, our issue was different, we were having the same AlertDialog twice because of a bug in the test routine but the old intl utils due to some async timing was making available just one and so our test was passing even if it shouldn't. Now we corrected the test and fixed the issue that was not related to intl
