### ISSUE TITLE
How to use Escaping syntax

### ISSUE THREAD

**Issue by jack24254029** [localizely/intl_utils#102]
I want to use `flutter_richtext_composer`, but the keyword is conflict between `flutter_richtext_composer` and `intl_utils`

I find the official document of Flutter that says set `use-escaping: true` to skip tokens, such as { and }, as normal characters.

But I don't know how to set it when I use `intl_utils` and I don't find the `l10n.yaml` that `intl_utils` use.

Ref: 
https://pub.dev/packages/flutter_richtext_composer
https://docs.flutter.dev/development/accessibility-and-localization/internationalization#escaping-syntax

**Comment by aleksakrstic** [comment]
`use-escaping` is not related to `intl_utils` [usage](https://localizely.com/blog/flutter-localization-step-by-step/?tab=automated-using-flutter-intl), but it is related to using [Flutter's gen_l10n](https://localizely.com/blog/flutter-localization-step-by-step/?tab=using-gen-l10n) tool.

Hence closing this issue
