### ISSUE TITLE
Dart SDK 3.0.0 version solving error

### ISSUE THREAD

**Issue by deakjahn** [localizely/intl_utils#103]
With the new 3.0.0 SDK installed, the following error appears:

```
--no-color pub global activate intl_utils ">=1.0.0 <2.0.0"
Package intl_utils is currently active at version 2.8.2.
Resolving dependencies...
The current Dart SDK version is 3.0.0.

Because pub global activate depends on intl_utils <2.0.0 which doesn't support null safety, version solving failed.

The lower bound of "sdk: '>=2.2.2 <3.0.0'" must be 2.12.0 or higher to enable null safety.
For details, see https://dart.dev/null-safety
Process finished with exit code 1
```

Android Studio, plugin 1.18.1-2020.3

Doctor:

```
[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.22621.1702], locale en-US)
    • Flutter version 3.10.0 on channel stable at E:\Android\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (2 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1
```

**Comment by deakjahn** [comment]
A major pain in the neck, but I found the workaround steps. As this is a breaking change that probably caught very many developers unawares, with a Dart upgrade that's very welcome and people do want to use all the new language constructs as soon as possible. @Izoran, could you chime in and solve it somehow? I'll send my PR but I'll also describe the apparent problems there.

The solution is in three steps. First, I modified `intl_utils` to support SDK 3. It will stay in my GitHub repo as long as necessary, so feel free to rely on it: https://github.com/deakjahn/intl_utils

1. Add the following to your `pubspec.yaml`. Upgrade your dependencies as usual.

```
dev_dependencies:
  ...
  intl_utils:
    git:
      url: https://github.com/deakjahn/intl_utils
      ref: master
```

2. Deactivate the global plugin from the terminal you use (IDE or otherwise):

    flutter pub global decativate intl_utils

3. And now the pain in the neck, translations are not generated automatically now whenever there's a change in an `.arb` file but have to be initiated manually. Keep your terminal window open and use it whenever needed:

    flutter pub run intl_utils:generate

At least it works...

**Comment by lzoran** [comment]
I guess the main problem here is that the [Flutter Intl plugin](https://plugins.jetbrains.com/plugin/13666-flutter-intl) for Android Studio forces the wrong version of the `intl_utils` package here ([similar issue](https://github.com/localizely/flutter-intl-intellij/issues/97)).

If that is the case, upgrading the Flutter Intl plugin to the `1.18.2` should solve this issue.

**Comment by deakjahn** [comment]
It's easy if you fix it. :-) Thanks.

**Comment by deakjahn** [comment]
(I removed my repo because it's no longer needed.)
