### ISSUE TITLE
Issue with auto generation of translation.

### ISSUE THREAD

**Issue by jineshcygnet** [localizely/intl_utils#11]
When i update/add in intl_en.arb file which is main_locale as pubspec file, i am facing below issue. 

![Screenshot 2020-11-25 at 4 46 44 PM](https://user-images.githubusercontent.com/75015887/100227214-d3a5b280-2f46-11eb-84e8-6b264930b59d.png)

**Comment by aleksakrstic** [comment]
Hi @jineshcygnet 
Could you check if you have unexpected usage of `{` or `}` characters or invalid Plural/Gender/Select syntax in translations inside arb files?
More info about expected Plural/Gender/Select syntax here: https://localizely.com/flutter-arb/

We should definitely improve log messages in such cases, so would like to hear from you if that was the cause.

**Comment by jineshcygnet** [comment]
Oh, I solved it by deleting generate folder and executed again so generate folder created again and all working fine.
