### ISSUE TITLE
[Question] How to include countryCode in generated l10n file 

### ISSUE THREAD

**Issue by thaiquoctoanvn** [localizely/intl_utils#110]
Hi Team, I wondered how I can include countryCode in each locale in supportedLocales list when running generate command. 
The current supportedLocales list I get like this:

```
List<Locale> get supportedLocales {
    return const <Locale>[
      Locale.fromSubtags(languageCode: 'en'),
      Locale.fromSubtags(languageCode: 'es'),
      Locale.fromSubtags(languageCode: 'vi'),
    ];
}
```

And what I expect like this:

```
List<Locale> get supportedLocales {
    return const <Locale>[
      Locale.fromSubtags(languageCode: 'en', countryCode: 'us'),
      Locale.fromSubtags(languageCode: 'es', countryCode: 'es'),
      Locale.fromSubtags(languageCode: 'vi', countryCode: 'vn'),
    ];
}
```
or some thing that I can get countryCode from the generated file. Is there any more config option for my case? Thanks

**Comment by lzoran** [comment]
Naming the arb files according to the specific language they correspond to should work.

For example: 
English (United States) → `intl_en_US.arb`
Spanish (Spain) → `intl_es_ES,arb`
Vietnamese (Vietnam) → `intl_vi_VN.arb`
