### ISSUE TITLE
Feature request: description as comments on getters

### ISSUE THREAD

**Issue by amrbashir** [localizely/intl_utils#12]
I'd like to have the description of each arb string to be converted to a comment on the corresponding getter along with current implementation.

instead of this:

![image](https://user-images.githubusercontent.com/48618675/100457058-01673480-30ca-11eb-815a-9757352c8fb4.png)

I'd like this:

![image](https://user-images.githubusercontent.com/48618675/100457145-2cea1f00-30ca-11eb-8500-2ba3ee2986d7.png)

This way flutter/dart extension can provide intellisense like this.

![image](https://user-images.githubusercontent.com/48618675/100457203-4d19de00-30ca-11eb-9a0f-3e8fd906c90a.png)

**Comment by aleksakrstic** [comment]
Hi @AmrBinBashir 
Thanks for suggestion!
We will consider it for one of upcoming package updates.
