### ISSUE TITLE
when i add new word in .arb it dosen't work

### ISSUE THREAD

**Issue by AliSabbar** [localizely/intl_utils#130]
Describe the bug
whene i add new word to .arb file and try to use it in ui it not apper in suggestion and i if i typed manually it still give me error
The getter 'newLocale' isn't defined for the type 'S'.
i use the packge flutter intl from vscode to set up my localization in my apps when i run project on flutter version like 3.22.1 it work fine but when i updated to flutter 3.24.2 it won't work any more when i try to run the command in terminal
flutter pub global run intl_utils:generate 
it give me error:
![image](https://github.com/user-attachments/assets/bcfad8d2-d524-4243-b9b2-a3fea1096ca6)
To Reproduce
usage in UI
`void main(List<String> arguments) {
print(S.of(context).newLocale)
}`
System info
flutter doctor -v
![image](https://github.com/user-attachments/assets/58abcda5-3342-43e0-ba4c-bfaf0a359ecd)

**Comment by lzoran** [comment]
Hi @AliSabbar,

Could you check if reactivating the `intl_utils` package helps? 
There is some issue with the Flutter cache after a Flutter upgrade.

Steps:
1. Deactivate intl_utils package:
    ```flutter pub global deactivate intl_utils```

2. Edit one of your ARB files and save to trigger `intl_utils` activation and generation of localization code.

**Comment by AliSabbar** [comment]
> Hi @AliSabbar,
> 
> Could you check if reactivating the `intl_utils` package helps? There is some issue with the Flutter cache after a Flutter upgrade.
> 
> Steps:
> 
> 1. Deactivate `intl_utils` package:
>    `flutter pub global deactivate intl_utils`
> 2. Edit one of your ARB files and save to trigger `intl_utils` activation and generation of localization code.

Thank You it work again
