### ISSUE TITLE
Add support to configure the line-length of the generated files

### ISSUE THREAD

**Issue by M-Ahal** [localizely/intl_utils#132]
Flutter intl_utils plugin generates the translation files with the default line width of 80. My project, for instance, uses the a line-length of a 100 for all dart files. The dart format checks in my CICD also check for this.
Is there a way of setting that to a 100. Otherwise, now I have to keep running `dart fornat -l 100 .` after changing an ARB file?

**Comment by lzoran** [comment]
Duplicate of #128
