### ISSUE TITLE
Throw error when parsing specific TR words

### ISSUE THREAD

**Issue by RaymondGsc** [localizely/intl_utils#135]
Here is part of my intl_tr.arb file

`
{
"back_new_chest_unlock_day": "Gün ${arg1}'da açılır",
"@@locale": "tr"
}
`

And the output was

`Building package executable... `
`Built intl_utils:generate.`
`ERROR: Failed to generate localization files.`
`type 'Null' is not a subtype of type 'int' of 'index'`

**Comment by lzoran** [comment]
Hi @RaymondGsc,

Could you check if the `"back_new_chest_unlock_day"` localization message in your main localization file contains the same placeholder (`{arg1}`) that you use in the `intl_tr.arb` file?

**Comment by RaymondGsc** [comment]
> Hi @RaymondGsc,
> 
> Could you check if the `"back_new_chest_unlock_day"` localization message in your main localization file contains the same placeholder (`{arg1}`) that you use in the `intl_tr.arb` file?

Sorry I made a foolish mistake. Please close this issue.

**Comment by neustaTerasa** [comment]
Thanks for this thread, I had the exact problem, @lzoran described. But it took me several hours to find it out. Localization files are maintained by the customer, so I wasn't aware about that problem. So, a better error message would be great!
