### ISSUE TITLE
NULL-safety

### ISSUE THREAD

**Issue by felix-barz-brickmakers** [localizely/intl_utils#14]
This package should provide a nullsafe version. Since both, `flutter_localizations` and `intl` now provide a nullsafe preview version, this package should do the same, so we can generate nullsafe translations.

**Comment by felix-barz-brickmakers** [comment]
Note: I do not mean that this package has to be ported to nullsafety yet. But it should provide some parameter to be configured to generate nullsafe code.

**Comment by aleksakrstic** [comment]
Hi @felix-barz-brickmakers 
There is a plan to support null-safety, just it is blocked by https://github.com/dart-lang/intl_translation/issues/118
Linked issue: https://github.com/localizely/flutter-intl-intellij/issues/36

**Comment by Wikiwix** [comment]
@aleksakrstic One major improvement until then would be to add `//@dart=2.9` as the first line to all generated code for not having to touch the generated code manually every time it is generated.

**Comment by lzoran** [comment]
Hi @felix-barz-brickmakers, @Wikiwix,

I've just checked the state of the dependencies of the `intl_utils` package regarding the migration to the null-safety.

Most of the packages we depend on have migrated, and I hope the remaining few will soon.
Annotating the generated source files with the specific Dart version indeed eases migration. The main disadvantage of that is that it requires a lot of effort to maintain and document those changes through the migration process, especially if we expect that the remaining few packages will soon migrate too.

Knowing the demand for null-safety support, we are watching all our dependencies, and we will support it as soon as we can.

**Comment by dramcio** [comment]
@Wikiwix it is possible to implement at least your solution?

**Comment by Wikiwix** [comment]
> @Wikiwix it is possible to implement at least your solution?

I mean I opened MRs in both repos for this, so nothing more I can do.

But what you *can* use in the meantime instead of the official release (Of course you can clone it yourself as well ¯\_(ツ)_/¯ ):

```yaml
  intl_translation:
    git:
      url: https://github.com/Wikiwix/intl_translation.git
      ref: master
  intl_utils:
    git:
      url: https://github.com/Wikiwix/intl_utils.git
      ref: master
```

If you want to use the extension as well, call the following:
 `dart pub global activate --source git "https://github.com/Wikiwix/intl_utils.git"`

**Comment by navaronbracke** [comment]
Is there any reason why we don't use Flutter's `gen-l10n` command instead? That is being migrated to NNBD. AFAIK `intl-translation` seems out-of-date for a while now. See [#70415](https://github.com/flutter/flutter/pull/70415)

**Comment by aleksakrstic** [comment]
Hi @felix-barz-brickmakers @Wikiwix @dramcio @navaronbracke 
New version `intl_utils 2.0.0` is released now. It uses null-safety and works with Flutter 2.0. 
Would like to hear your feedback if everything is ok on your side.

**Comment by navaronbracke** [comment]
@aleksakrstic Now that `intl_utils` supports nullsafety, will the IDE plugins for VS Code & Intellij/ Android Studio get an update (so they use the null safe version of intl_utils) ?

**Comment by aleksakrstic** [comment]
Sure @navaronbracke 
It might take a few days for IntelliJ/AS due to their approval process.

**Comment by Wikiwix** [comment]
I had a look at the new release and the fact that `Strings.of(context)` is nullable is not really practicable.

There has to be a way around that. We cannot be expected to have a default for that. The code generation and type safety was the reason to choose your solution in the first place.

**Comment by navaronbracke** [comment]
@Wikiwix I agree, the nullable translations class would force developers to add the `!` operator to each call to the translations class.

I checked the Flutter docs example for InheritedWidgets and they do this now:
```
static FrogColor of(BuildContext context) {
    final FrogColor? result = context.dependOnInheritedWidgetOfExactType<FrogColor>();
    assert(result != null, 'No FrogColor found in context');
    return result!;
}
```
I find using an assertion on null and using the `!` operator inside the static function a better way of doing it. 
The only issue here is if a developer forgets to set up his delegate in the tree. This process is documented in the Flutter docs and the plugin. Thus I'd suggest to use a warning message in the assert. E.g. `<TranslationClassName> not found in the widget tree. Did you set up your delegate?`

**Comment by navaronbracke** [comment]
@Wikiwix There is currently a PR that addresses this issue. It adds the aforementioned assert & cast to the `of(BuildContext context)` function and adds a `maybeOf(BuildContext context)` function that can return null. See #27
