### ISSUE TITLE
What 'type's can I use for placeholders?

### ISSUE THREAD

**Issue by drekka** [localizely/intl_utils#24]
Perhaps I've missed something but I've been trolling the inter webs for hours trying to figure this out. 

AS far as I can tell I can use the 'String' type for a placeholder like this in a `*.arb` file:

```
"workedHoursGraphCriteriaLastNDays": "Last {days} days",
  "@workedHoursGraphCriteriaLastNDays": {
    "placeholders": {
      "days": {
        "type": "String"
      }
    }
  }
```

That works. Now I want to inject a number but I can't seem to find any docs on what type to specify or in fact, any other types. I tried `int` but the generator fails saying it isn't supported and to check the `NumberFormat` class for details. I also tried 'number', 'Number', 'Int', 'int', 'double', 'Decimal' and others. I'd either get told to look at 'NumberFormat' or a compilation failure.

Unfortunately `NumberFormat` isn't that helpful. It knows nothing of '*.arb' files and I've not been able to find anything on the web that talks about what the options are.

Is there a list of value types somewhere?

**Comment by aleksakrstic** [comment]
Hi @drekka 
You don't need to define the types in ARB files for placeholders. It will be enough to define it in ARB file like this:
```
"workedHoursGraphCriteriaLastNDays": "Last {days} days",
"@workedHoursGraphCriteriaLastNDays": {
    "placeholders": {
       "days": {}
    }
}
```
Or even just 
```
"workedHoursGraphCriteriaLastNDays": "Last {days} days",
```
It will generate a key getter that accepts any object for the placeholder, but you might want to format it before you pass it to the string key getter.
