### ISSUE TITLE
intl 0.17.0 and Flutter 2.0 support

### ISSUE THREAD

**Issue by danielgomezrico** [localizely/intl_utils#26]
I just updated to flutter 2 and got:

```bash
Because client depends on flutter_localizations any from sdk which depends on intl 0.17.0, intl 0.17.0 is required.
So, because client depends on intl 0.16.1, version solving failed.
```

 So I updated that and now I get:
```bash
Because intl_utils 1.9.0 depends on intl_translation 0.17.10+1 which depends on intl >=0.15.3 <0.17.0, intl_utils 1.9.0 requires intl >=0.15.3 <0.17.0.
So, because client depends on both intl 0.17.0 and intl_utils 1.9.0, version solving failed.
```

**Comment by aleksakrstic** [comment]
Hi @danielgomezrico 
We are currently working on a new version of `intl_utils` that solves issue regarding https://github.com/localizely/intl_utils/issues/14 and mentioned dependency versions.
We expect it to be released soon.

**Comment by proninyaroslav** [comment]
And please upgrade `analyzer` to 1.1.0 version.

**Comment by danielgomezrico** [comment]
@proninyaroslav is that comment is related to this issue?

**Comment by aleksakrstic** [comment]
Hi @danielgomezrico 
New version intl_utils 2.0.0 is released now. It uses null-safety and works with Flutter 2.0.
Would like to hear your feedback if everything is ok on your side.

@proninyaroslav the dependency issue with `analyzer` should be solved as well.
