### ISSUE TITLE
intl_utils using older version

### ISSUE THREAD

**Issue by rockarts** [localizely/intl_utils#33]
Hello, 

We are trying to use intl_utils in our CI pipeline using the following command:

`flutter packages pub global activate intl_utils && flutter pub global run intl_utils:generate`

When we run the above command we get version 1.9.0 of intl_utils. Shouldn't we get 2.1.0?

**Comment by lzoran** [comment]
Hi @rockarts,

I guess that you are using the older Flutter version that does not support null-safety within CI.

*In case that your project does not support null-safety, you should use the `intl_utils 1.9.0` (the `intl_utils >=2.0.0` will generate null-safety localization code).
