### ISSUE TITLE
`intl_translation` has not been updated to work with latest `intl_utils`

### ISSUE THREAD

**Issue by lpickford-pixelbeard** [localizely/intl_utils#34]
The current `intl_translation` package has a dependency of `intl: '>=0.15.3 <0.17.0'` meaning that if this is used as part of testing then it is currently not possible to upgrade to flutter 2.x and use `intl_utils`.

**Comment by aleksakrstic** [comment]
Hi @lpickford-pixelbeard 
You can use `intl_utils 2.1.0` and newer versions with Flutter 2.x

Do you still use `intl_translation` directly for anything?

**Comment by lpickford-pixelbeard** [comment]
Hi @aleksakrstic ,

Yes we have it as a test dependency as per the docs, but we can't do that now as it's not compatible. Would we be better generating the localisations before running tests instead and removing this dependency?

**Comment by aleksakrstic** [comment]
Generally you don't need to use `intl_translation` in your dependencies if you use `intl_utils`.

I am not sure how do you use `intl_translation` for the tests. Could you give more info on that?

**Comment by lpickford-pixelbeard** [comment]
I was just following the docs and thought it was a dependency for tests, if this is not the case feel free to close this :)
