### ISSUE TITLE
[intl_utils: 2.1.0] _current != null': No instance of S was loaded.

### ISSUE THREAD

**Issue by deimantasa** [localizely/intl_utils#35]
Hello team,

We've just found one very funky area within localisation while using tests.

Consider using class `test_class.dart`
```
class TestClass {
  String name = S.current.title;
}
```

And test class `test_class_test.dart`
```
main() {
  final strings = S();

  test("Test", () {
    TestClass testClass = TestClass();
    expect(testClass.name, strings.title);
  });
}
```

Given `title` is localised, when we run the test, we will see this error
```
Failed assertion: line 21 pos 12: '_current != null': No instance of S was loaded. Try to initialise the S delegate before accessing S.current.
```

Checking upon it, that's correct
```
static S get current {
    assert(_current != null, 'No instance of S was loaded. Try to initialise the S delegate before accessing S.current.');
    return _current!;
  }
```

`S` was never initialised, because we are loading model via test. 
My question is, why there is an assertion? If `S` is null, shouldn't `S` be initialised automatically?

```
static S get current {
    if(_current == null) _current = S();
    return _current!;
  }
```

This way particular error is avoided. Was wondering, is it a bug or this is expected behaviour? If it's expected behaviour, what's the recommended way to handle it?

Before null safety, one can simply check if `current` is null and if it it - assign `S()`. But now, since `current` is defined as non-nullable we cannot check for its nullability.

TIA

**Comment by lzoran** [comment]
Hi @deimantasa,

Thanks for reporting this and creating the PR!

The localization delegates should be initialized before the usage of the `current`, `S.of(context)` or `S.maybeOf(context)` (reason why assertion was added).

The main challenge I see here is how to test model classes that depend on localization.
Not sure, but maybe [this example](https://github.com/localizely/flutter-intl-plugin-sample-app/blob/master/test/localized_widget_test.dart) can help you or give you some idea.

Also, instantiating the `S` class without localization initialization (setting `localizationsDelegates`, `supportedLocales`, `locale`, etc.) won't load localization messages and set up the app locale.

**Comment by deimantasa** [comment]
Hi @lzoran ,

Thanks for reply. That's exactly the issue that we are testing not the widget but model itself. We don't want any UI render interference, and `strings` plays crucial part in identifying if correct value was being resulted. 

If we are testing via widget - it's all good, because as you've mentioned, we do initialisation within its root. 

With current PR everything works as expected and our tests are working well. I'm not entirely sure, why this fix couldn't be applied? 

It's also very interesting, because you've mentioned that - ` localization delegates should be initialized before the usage of the current, S.of(context) or S.maybeOf(context)` - yet with current PR they are not initialised there and our tests spins perfectly as expected.

And yes, it's pretty specific use-case and as I've mentioned before - prior `null-safety` we could have dealt with that with additional `null check` outside. But now, since the variable is not nullable - we can't have that `null check` anymore.


We could potentially introduce some flag as `isUnitTest` or something, so that assertion would be avoided. Anyways, would love to brainstorm other ways, how could it be solved, if you think current fix is a no-go.


Cheers

**Comment by lzoran** [comment]
Hi @deimantasa,

> It's also very interesting, because you've mentioned that - localization delegates should be initialized before the usage of the current, S.of(context) or S.maybeOf(context) - yet with current PR they are not initialised there and our tests spins perfectly as expected.

- I believe that lookup message logic fallback to the passed `messageText` in case localization messages are not loaded.

Does a bit different approach work for you?

```
main() async {
  final strings = await S.load(Locale.fromSubtags(languageCode: 'en')); // mimic localization delegate init

  test("Test", () {
    TestClass testClass = TestClass();
    expect(testClass.name, strings.title);
  });
}
```

**Comment by deimantasa** [comment]
Hi @lzoran ,

Yes, this solution seems to work. But I'm still little confused about 
```
static S get current {
    assert(_current != null, 'No instance of S was loaded. Try to initialise the S delegate before accessing S.current.');
    return _current!;
  }
```
Could you explain why solution like this is there? Because as far as I tested, my deployed solution didn't break anything. And I'm curious what's the reason behind having `assertion` with `null` for a Singleton.

Also preferably, since this case is being hit only in tests so far, why this approach would not be accepted?
```
  static S test() {
    if(_current == null) _current = S();
    return _current!;
  }
```
With comments, we can clearly specify that this singleton initialisation is only used for `testing` purpose. And it seems much cleaner. But I guess you know more about it than me.

Looking forward!

Cheers

**Comment by lzoran** [comment]
Hi @deimantasa,

Sorry for the late response.

I agree with you that the assertion is not the best solution here. 
The problem with the "forced" instantiation is that it will let you invoke localization getters/methods on the `current` where localization messages are not loaded. That way, we may introduce unexpected behavior in the app. :/

Also, the proposed solution works well because of the fallback logic within the `Intl.message`.
The generated code contains the `messageText`, that is used as a fallback in case localization messages are not loaded.
Although this may be OK in most cases, how would we test model classes for non-main locales?

```
/// `Home page`
String get pageHomeTitle {
  return Intl.message(
    'Home page', // messageText is a main translation
    name: 'pageHomeTitle',
    desc: '',
    args: [],
  );
}
```

**Comment by deimantasa** [comment]
No worries. Alright, let's keep it like it is then. As long as there is some kind of solution, it's alright.

Cheers mate!
