### ISSUE TITLE
This requires the 'non-nullable' language feature to be enabled.

### ISSUE THREAD

**Issue by TimurMukhortov** [localizely/intl_utils#36]
Hello 

I have a problem while generating.

Can you help me with it?

<img width="1218" alt="Screenshot 2021-03-25 at 19 29 38" src="https://user-images.githubusercontent.com/20271476/112508245-714baa00-8da0-11eb-9e23-189bb07d0034.png">
<img width="313" alt="Screenshot 2021-03-25 at 19 29 57" src="https://user-images.githubusercontent.com/20271476/112508322-7c9ed580-8da0-11eb-9c0c-24b35ac5495e.png">
<img width="787" alt="Screenshot 2021-03-25 at 19 30 12" src="https://user-images.githubusercontent.com/20271476/112508369-858fa700-8da0-11eb-8c7c-31dc078bc7af.png">

**Comment by lzoran** [comment]
Hi @TimurMukhortov,

It looks that you are using a null-safe version of the `intl_utils` package in your project, that generates null-safe localization files.

Not sure if you want to support null-safety in your project (environment sdk is not set to the `">=2.12.0-0 <3.0.0"`)?
If not, usage of the `intl_utils 1.9.0` should fix this issue.

**Comment by TimurMukhortov** [comment]
@lzoran yes. sorry. it was my fault. thank you.
