### ISSUE TITLE
[Proposal] Nested objects in ARB files

### ISSUE THREAD

**Issue by navaronbracke** [localizely/intl_utils#40]
With larger translation files, organizing them can get quite difficult.

As the ARB files that are used for generating delegates are in JSON format,
we could perhaps use nested JSON objects?

For example:
```
{
  "nested": {
     "first": "something",
     "second": "something {param} else"
  }
}
```

could become `String get nestedFirst => _nested["first"]` where `_nested` is a `Map<String,String>` that is filled with `Intl.message` and siblings.
In essence, we add an extra parsing case for a Map to the delegate generation.

**Comment by aleksakrstic** [comment]
Hi @navaronbracke 
Thanks for the proposal.
It would diverge from ARB file structure specification so I think we shouldn't go that way for now.

Could you share what particularly is difficult in your case in organizing ARB files?
Maybe there is another solution to it.

**Comment by navaronbracke** [comment]
Well, in my case there are a lot of strings like the following:
```
  "RideAttendeeScanningProcessScanLabel": "Scan",
  "RideAttendeeScanningProcessAddMembersLabel": "By Hand",
  "RideAttendeeScanningPreparingScan": "Preparing Scan",
  "RideAttendeeScanningNoMembers": "Cannot start a scan, there are no riders",
  "RideAttendeeScanningGoBackToDetailPage": "Return to detail page",
  "RideAttendeeScanningPermissionDenied": "Scan aborted, permission was denied.",
  "RideAttendeeScanningPermissionDeniedDescription" : "Scanning requires permission to use your location.",
  "RideAttendeeScanningBluetoothDisabled": "Scan aborted, Bluetooth is disabled",
  "RideAttendeeScanningGoToSettings": "Go to Settings",
  "RideAttendeeScanningRetryScan": "Retry Scan",
  "RideAttendeeScanningSkipScan": "Skip Scan",
  "RideAttendeeScanningContinue": "Continue",
  "RideAttendeeScanningManualSelectionEmptyList": "There are no riders to choose from",
  "RideAttendeeScanningDeviceWithMultiplePossibleOwnersLabel": "{amount} riders have a device with this name",
  "RideAttendeeScanningUnresolvedOwnersListTooltip": "Some scanned devices have multiple possible owners. You can select the attending owners here.",
``` 

A lot of these strings have a key that starts with the same prefix `RideAttendeeScanning`, it would be convenient if I could reduce duplication by using the method as described above.

**Comment by aleksakrstic** [comment]
I see. Thanks for the info.
Maybe you could use abbreviated prefixes if that bothers you.
Will close the ticket for now and reopen in the future if we come back to this topic.

**Comment by mdeandrea-mrmilu** [comment]
Maybe [this issue](https://github.com/flutter/flutter/issues/71729#issuecomment-852059076) can help to organize by sections

**Comment by guplem** [comment]
This would be a great feature... I am having the same issues

**Comment by egyleader** [comment]
since .arb files are used in localizations in flutter I think this is a core feature as any kind of medium to large applications will have hundreds of keys and differentiating them by a prefix in the key name is not optimal in any case , please reopen this issue .
