### ISSUE TITLE
[BUG] Failed generation when translation string contains \ and $

### ISSUE THREAD

**Issue by schultek** [localizely/intl_utils#43]
I have a string in my .arb files that contains a `\`, something like:

```json
{
  "my_string": "a\\b c\\$d",
}
``` 

Note that the `\`is already escaped, to be treated as a normal character.

When I run ` intl_utils:generate` it fails with the error:
```
Error in parsing [redacted]/generated/l10n.dart, no messages extracted.
ERROR: Failed to generate localization files.
Invalid argument(s): Parsing errors in [redacted]/generated/l10n.dart
```

The `generated/l10n.dart` file is actually generated, but none of the `generated/intl/messages_*.dart`.

Here is the relevant part of the generated file:

```dart
/// `a\b c\$d`
String get my_string {
  return Intl.message(
    'a\b c\\$d',
    name: 'my_string',
    desc: '',
    args: [],
  );
}
```

There are two separate issues here:
1. The first `\` in the dart string in line 4 is not properly escaped (should be `\\`) and treated as a control sequence. 
2. The second `\` **is** properly escaped, however the following '$' is not, and therefore treated as a string interpolation symbol. This one actually leads to the above error.

**Comment by lzoran** [comment]
Hi @schultek,

Thanks for reporting this! 

The fix is available in the latest version - `intl_utils 2.2.0`.
