### ISSUE TITLE
Problem with HTML inside l10n

### ISSUE THREAD

**Issue by sdurban** [localizely/intl_utils#48]
Hello!

I have a strange use case in my company. One of the sentences in the arb files have text with HTML code and variables. This was working fine before commit https://github.com/localizely/intl_utils/commit/b3297b95b70099c9c80f099de9a24e1020a8b6d5

In that commit the parser nonIcuMessageText is removed from the parse function (by removing simpleText). Without this parser the code ends up with a null exception.

Problem:
![imagen](https://user-images.githubusercontent.com/4395258/117874421-3abee580-b2a1-11eb-9582-f4322c2c575f.png)

Debug:
![imagen](https://user-images.githubusercontent.com/4395258/117874642-83769e80-b2a1-11eb-9c5d-766fc567a0b3.png)
![imagen](https://user-images.githubusercontent.com/4395258/117876148-50cda580-b2a3-11eb-957c-55b80a3ddd60.png)

(VariableSubstitution(null) is the problem here since l10n have no parameters in that function)

It can be fixed changing the icu_parser.dart:

`Parser get contents =>
      pluralOrGenderOrSelect | parameter | messageText | nonIcuMessageText;` (https://github.com/sdurban/intl_utils/commit/3389dfbd9a455612058d08fa939f6a4ebd72d2dd)

But this breaks a lot of test cases... Not sure what to do here... Any Advice?

**Comment by lzoran** [comment]
Hi @sdurban,

Thanks for reporting this!

You are right. The latest changes in the parser caused the bug. We will try to release the fix for it in one of the upcoming releases.
I'll check the proposed solution. In the meantime, you can use the `intl_utils 2.1.0` as an alternative (if that helps).

**Comment by lzoran** [comment]
Duplicate of #44

**Comment by GabrielCR99** [comment]
Hello, @lzoran!
I'm also having this issue, even though I'm using intl_utils 2.1.0.
The thing is, when there's even a single HTML code inside de .arb file, it shows the following error: "The expression doesn't evaluate to a function, so it can't be invoked".
Here's an example of my case: "bank_account_delete": "Are you sure you want to delete <b>{bank} account {account}?</b>".
Thanks in advice!

**Comment by lzoran** [comment]
Hi @GabrielCR99,

I've checked generation for the posted message, and it works fine on my machine with `intl_utils 2.1.0`.

Could you please share the generated `bank_account_delete` method from the `generated\l10n.dart` file, the generated code for the `bank_account_delete` message from the `generated\intl\messages_*.dart` files, and also the way the `bank_account_delete` method is called on the `S` class?

Checking the *"The expression doesn't evaluate to a function, so it can't be invoked"* error message on the internet, I'm more convinced that this error is not related to the generated code, but to the way of calling the localized message. But maybe, I missed something :/.

**Comment by GabrielCR99** [comment]
> Hi @GabrielCR99,
> 
> I've checked generation for the posted message, and it works fine on my machine with `intl_utils 2.1.0`.
> 
> Could you please share the generated `bank_account_delete` method from the `generated\l10n.dart` file, the generated code for the `bank_account_delete` message from the `generated\intl\messages_*.dart` files, and also the way the `bank_account_delete` method is called on the `S` class?
> 
> Checking the _"The expression doesn't evaluate to a function, so it can't be invoked"_ error message on the internet, I'm more convinced that this error is not related to the generated code, but to the way of calling the localized message. But maybe, I missed something :/.

Hi, @lzoran !
Actually, I just missed the HTML bold tag `<b>`, so the final result is actually: `Are you sure you want to delete <b>{bank} account {account}?</b>` but anyway, it still doesn't work. 

Here's the generated method from the `generated\l10n.dart` 

```dart
String get bank_account_delete {
    return Intl.message(  
      'Você tem certeza que deseja excluir <b>{bank} conta {account}?</b>',
      name: 'bank_account_delete',
      desc: '',
      args: [],
    );
  }
```
And finally, this is the way the `bank_account_delete` method is being called on the S class:
```dart
S.of(context).bank_account_delete(bankAccount.bank.name, bankAccount.account)
```

**Comment by GabrielCR99** [comment]
Hey, @lzoran,

Don't worry, man! You're not bothering me, I'm the one who apologizes if I'm boring.

Even though I'm using intl_utils 2.1.0 in both pubspec.yaml and with 
```dart 
flutter pub global activate intl_utils 2.1.0
```
It still doesn't work, unfortunately.


I'm going to show you the 3 ARB files that I use in my project (en_US, pt_BR which is the main_locale and es).

en_US: 
```json
    "bank_account_delete": "Are you sure you want to delete <b>{bank} account {account}?</b>",
```

pt_BR (main_locale): 
```json
    "bank_account_delete": "Você tem certeza que deseja excluir <b>{bank} conta {account}?</b>",
```
es: 
```json
     "bank_account_delete": "¿Estás seguro de que deseas eliminar la <b>{bank} cuenta {account}?</b>",
```
Here's the error showing on the page which I call the method
![image](https://user-images.githubusercontent.com/42328188/118690672-aabbf700-b7de-11eb-8e15-fef3c3524ea9.png)
![image](https://user-images.githubusercontent.com/42328188/118690853-d9d26880-b7de-11eb-8466-2aafe1d07b5c.png)

**Comment by lzoran** [comment]
Hi @GabrielCR99,

Thanks for provided info!

I got the same error message as you, but with the `intl_utils 2.2.0`.

I guess that you have installed the Flutter Intl plugin for your IDE, which overwrites the `2.1.0` version that works fine.
If that is the case, you can disable the Flutter Intl plugin by updating the `flutter_intl` config under `pubspec.yaml` file, and then manually run the `intl_utils 2.1.0` from the root of a project (each time you update your arb files).

```
...
flutter_intl:
  enabled: false
  main_locale: pt_BR
...
```

Note that the Flutter Intl plugin globally activates a specific version of the `intl_utils` package and uses it (only one version of the package can be globally active).

**Comment by GabrielCR99** [comment]
Hello again, @lzoran!

I didn't notice that the Flutter Intl plugin was overwriting the 2.1.0, just disabled it, and it's now working perfectly.

Many thanks for the help!

Sorry for the bothering all this time. Your package is absolutely amazing, congratulations! I've been using it since 1.5.0, if I remember correctly :)

**Comment by lzoran** [comment]
Glad to hear that @GabrielCR99!

**Comment by lzoran** [comment]
Hi @sdurban, @GabrielCR99,

The issue with tags within translations is fixed with the latest version of the `intl_utils` package (`2.4.0`).

**Comment by sdurban** [comment]
Hi,

Tested today works like a charm, thank you guys!
