### ISSUE TITLE
[Question] How can I generate arb file from dart file ?

### ISSUE THREAD

**Issue by kristijorgji** [localizely/intl_utils#52]
Before migration to your library, I was using `intl_translation` and there it was possible to generate arb file based on the dart file
`localizations/app_localizations.dart` in my case

with structure like 
```
class AppLocalizations {
  AppLocalizations(this.localeName);

  static Future<AppLocalizations> load(Locale locale) {
    final String name =
        locale.countryCode.isEmpty ? locale.languageCode : locale.toString();
    final String localeName = Intl.canonicalizedLocale(name);
    return initializeMessages(localeName).then((_) {
      return AppLocalizations(localeName);
    });
  }

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  final String localeName;

  // login and registration
  String get prompt_email => Intl.message('Email', name: 'prompt_email');

  String get prompt_password =>
      Intl.message('Fjalёkalimi', name: 'prompt_password');

```

I could run before 
```
flutter pub run intl_translation:extract_to_arb --output-dir=lib/l10n lib/localization/app_localizations.dart
```
and this generated arb files, that could then modify/translate, then generate the dart files for every locale (which is working fine with your library this part too by ` flutter pub run intl_utils:generate`

**Comment by aleksakrstic** [comment]
Hi @kristijorgji 
The idea with `intl_utils` is to use your **ARB files as a source of truth** for your string keys, and only generate Dart files from it with `intl_utils:generate` command.
So, you should always add/manage string keys in ARB files and this package with generate all Dart code from it.

In case you installed Flutter Intl IDE plugin for your [VSCode](https://marketplace.visualstudio.com/items?itemName=localizely.flutter-intl) or [Android Studio](https://plugins.jetbrains.com/plugin/13666-flutter-intl), it will run this command automatically for you whenever you modify your ARB files. The string key getters will be available for usage in your Dart code right after that.

**Comment by kristijorgji** [comment]
@aleksakrstic Hi thanks for info, we migrated then to this version but are having some issue with bugs in your generator and plugin. Would be great if can get support to fix those soon then looking forward to manage translations online in your platform

Tickets for bugs i created are:
https://github.com/localizely/intl_utils/issues/58

and 
https://github.com/localizely/flutter-intl-intellij/issues/71
