### ISSUE TITLE
It doesn't work with Flutter Module?

### ISSUE THREAD

**Issue by iAllenC** [localizely/intl_utils#54]
I created a "Flutter Module" in Android Studio, added flutter_intl:  enabled: true to the pubspecs.yaml, then run pub get, and then click debug button. It fails with this logs:
No application found for TargetPlatform.ios.
Is your project missing an ios/Runner/Info.plist?
Consider running "flutter create ." to create one.

After I deleted flutter_intl:  enabled: true from the pubspecs.yaml, it works well. So I'm wondering, is it true that this doesn't support "Flutter Module" or I'm using it the wrong way? If I'm using it the wrong way, How can I use it in an Flutter Module?

My environments:
flutter 2.2.2 stable channel dart:2.13.3

**Comment by iAllenC** [comment]
Ok, I've figured out the problem, it is my mistake, sorry.

**Comment by AnujKumar7030** [comment]
I created flutter project  in Visual studio code, when I ran it. "Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project."  It showed this problem. Tell me how to fix it..!

**Comment by aleksakrstic** [comment]
@AnujKumar7030 Do you have a `pubspec.yaml` file in the root folder that you opened with Visual Studio Code?
