### ISSUE TITLE
[Feature] Option to specify additional lint rules in the auto-generated header

### ISSUE THREAD

**Issue by navaronbracke** [localizely/intl_utils#59]
Use case:

I have set up my own `analysis_options.yaml` file with a configuration for the linter rules to use and/or exclude.
If one or more rules in that file conflict with the autogenerated code of the plugin,
I get unnecessary analyzer warnings. (I.e. `always_use_package_imports` or `public_api_docs`)

Proposal: 

We should instead allow users to add an additional `ignore_for_file: <lints the user wants to ignore>` above or under the existing ones in the templates.
This would provide users with the ability to still somewhat configure the autogenerated file alongside the linter.

**Comment by aleksakrstic** [comment]
Solution is to exclude some files and directories from the analysis, as concluded in https://github.com/localizely/intl_utils/pull/51.

The analysis_options.yaml file:

    analyzer:
      exclude:
        - lib/generated/l10n.dart
        - lib/generated/intl/*
