### ISSUE TITLE
Can i Customize the directory structure for storing ARB files?

### ISSUE THREAD

**Issue by leeyisoft** [localizely/intl_utils#6]
我可以 自定义存放ARB文件目录结构 吗？
Can i Customize the directory structure for storing ARB files?

1 自定义存放ARB文件目录结构;
2 自定义 ./lib/generated/l10n.dart 文件 和 ./lib/generated/intl 目录 的目录结构;

1 Customize the directory structure for storing ARB files;
2 Customize the ./lib/generated/l10n.dart file and the "directory/lib/generated/intl" directory structure;

**Comment by aleksakrstic** [comment]
Hi @leeyisoft 
There is already one PR for custom ARB file paths https://github.com/localizely/intl_utils/pull/5

**Comment by aleksakrstic** [comment]
This is implemented with version `1.9.0`.

    flutter_intl:
        arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
        output_dir: lib/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
