### ISSUE TITLE
Generated Code not working

### ISSUE THREAD

**Issue by DevHachi** [localizely/intl_utils#62]
I've got a problem with the generated code for the internationalization.

`Localizations.of<I18n>(context, I18n); `

This line return an nullable object, but the generated class returns an not nullable object.

`static I18n of(BuildContext context) {
    return Localizations.of<I18n>(context, I18n);
  }`

This is code from the generated file "l10n.dart"

The second error I got in this file is the static current variable that is not initialized yet.

`static I18n current;`

And the last error is in the "messages_all.dart"

you return null in a not nullable context.

`MessageLookupByLibrary _findExact(String localeName) {
  switch (localeName) {
    case 'de':
      return messages_de.messages;
    case 'en':
      return messages_en.messages;
    default:
      return null;
  }
}`

`MessageLookupByLibrary _findGeneratedMessagesFor(String locale) {
  var actualLocale = Intl.verifiedLocale(locale, _messagesExistFor,
      onFailure: (_) => null);
  if (actualLocale == null) return null;
  return _findExact(actualLocale);
}`

This seems to be not null-sound-safety yet. It would be nice if this would be made possible because I love your plugin. 
(I use the android studio plugin by the way)

Here are my infos:
* Android Studio 2020.3.1 Patch 2
* Flutter 2.5.0
* Dart 2.14.0

**Comment by lzoran** [comment]
Hi @DevHachi,

The null-safety is already supported.

The Flutter Intl plugin checks an environment sdk version within the `pubspec.yaml` file and installs the appropriate version of the `intl_utils` package that later generates localization files.

```
environment:
  sdk: ">=2.12.0 <3.0.0" # this will generate null-safety code
```

**Comment by DevHachi** [comment]
Thx for the fast answer but this is already set.
```
environment:
  sdk: '>=2.12.0 <3.0.0'
```

**Comment by lzoran** [comment]
Interesting...

1. Could you check if you are using the latest version of the Flutter Intl plugin? 
I assume that it should be the `1.15.0-2020.3` version according to your IDE version.

2. Could you check the version of the globally activated `intl_utils` package?
It should be `2.4.0` (you can check it by running `flutter pub global list`).

3. Could you trigger a re-generation of the localization code to be sure that generated code is not null-safe?
Update one of the arb files and save it, or manually run `flutter pub global run intl_utils:generate` command in the console from the project's root.

**Comment by DevHachi** [comment]
Thx that was the right hint.

For all who want to know what did help me was to run this command in an terminal
`flutter pub global activate intl_utils 2.4.0`

This can be closed.

**Comment by globaljuli** [comment]
> Thx that was the right hint.
> 
> For all who want to know what did help me was to run this command in an terminal `flutter pub global activate intl_utils 2.4.0`
> 
> This can be closed.

Hi! In case it can be useful to someone else, I've had the same issue (Visual Studio Code plugin) and it was clearly something with the IDE. Disable or reinstall the plugin did not work nor deleting and regenerating the language files. Neither the `flutter pub global activate intl_utils`...

And I know it may sound stupid as it's usually something that you would try first, but the error was solved running first  `flutter pub global deactivate intl_utils` and after that, executing again the `flutter pub global activate intl_utils`. Hope it helps if you're here struggling with what more to do! 😊

Thanks guys for all the work with this!
