### ISSUE TITLE
Using apostrophe in strings produces analysis hint

### ISSUE THREAD

**Issue by zagalaga** [localizely/intl_utils#64]
My arb strings that contain an apostrophe produce a hint in the analysis:

arb:

"screen_info": "main screen's top bar."

messages file:

"screen_info": MessageLookupByLibrary.simpleMessage("main screen\'s top bar.")

result:

info: Remove unnecessary backslashes in strings. (unnecessary_string_escapes at...)

Can this be avoided? Is this a bug?

**Comment by lzoran** [comment]
Hi @zagalaga,

I have noticed that new Flutter projects by default include the `unnecessary_string_escapes` lint rule. Therefore, solving this problem really makes sense.

The latest release of the `intl_utils` package (`2.5.0`) now generates code that should not complain for the unnecessary string escapes and unnecessary string interpolations.

**Comment by zagalaga** [comment]
thanks!
