### ISSUE TITLE
Problem generating since version 2.5.0: type 'String' is not a subtype of type 'Map<String, Object?>'

### ISSUE THREAD

**Issue by JeroenvdV** [localizely/intl_utils#66]
The following error occurs in versions 2.5.0 and 2.5.1 and goes away when I activate 2.4.1: 

```
flutter pub global run intl_utils:generate
ERROR: Failed to generate localization files.
type 'String' is not a subtype of type 'Map<String, Object?>'
pub finished with exit code 2
```

This may be related to the following recent change, as this is one of few places in the code where that Map type occurs: https://github.com/localizely/intl_utils/commit/1f28c5d85ce1f1e9d82e6e95268501778ec15e41#diff-db18fad47f5ca583712e7a3c6ece37c8560f2dacc809a69ccfa016e581f31b2dR195

I'm sorry I don't have more info on reproducing at the moment.

**Comment by lzoran** [comment]
Hi @JeroenvdV,

Thanks for reporting this!

Could you check if you are using string or invalid map values for `placeholders` metadata somewhere in your arb files?

Invalid `placeholders`:
```
"stringKey1": "Your message",
"@stringKey1": {
  "placeholders": ""
},
"stringKey2": "Your message {name}",
"@stringKey2": {
  "placeholders": {
    "name": ""
  }
}
```

**Comment by JeroenvdV** [comment]
Thanks for your response, I did find an old placeholder of the form:
```
"stringKey2": "Your message {name}",
"@stringKey2": {
  "placeholders": {
    "name": "something intended as a default value"
  }
}
```
This fixed the problem for me.
