### ISSUE TITLE
Ignore or fix some lint errors and warnings

### ISSUE THREAD

**Issue by proninyaroslav** [localizely/intl_utils#7]
Hi. It would be great if you could fix these things:
1. `invalid_assignment` error in `messages_*.dart` files:
```Dart
class MessageLookup extends MessageLookupByLibrary {
  String get localeName => '...';

  final messages = _notInlinedMessages(_notInlinedMessages);
  static _notInlinedMessages(_) => <String, Function> {
    "..." : MessageLookupByLibrary.simpleMessage("...")
  };
}
```
Problematic line of code `final messages = _notInlinedMessages(_notInlinedMessages);`:
```
A value of type 'dynamic' can't be assigned to a variable of type 'Map<String, dynamic>'.
Try changing the type of the variable, or casting the right-hand type to 'Map<String, dynamic>'.
```
And also ignore `always_declare_return_types` or add return type to `_notInlinedMessages`.

2. `messages_all.dart` file: ignore `prefer_final_locals`, `prefer_final_in_for_each`, `avoid_redundant_argument_values`.
3. `l10n.dart` file: ignore `join_return_with_assignment`, `prefer_final_locals`, `prefer_final_in_for_each`, `avoid_redundant_argument_values`.

**Comment by lzoran** [comment]
Hi @proninyaroslav,

Thanks for reporting this issue!

Excluding generated files from analysis would solve this problem, but that probably won't work due to the still open [issue](https://github.com/dart-lang/sdk/issues/25551).

Note that `intl_utils` relies on the `intl_translation` package for generating `messages_*.dart` files and that we do not have control over it.
Regarding the lint warnings for `l10n.dart` file, we will add a fix for that in one of the upcoming releases.

**Comment by proninyaroslav** [comment]
@lzoran 
Implicit casts seem to have been fixes in 0.17.10+1, please update `intl_translation` version https://github.com/dart-lang/intl_translation/commit/f70d7ec83946aca1e9038d1f28cf2a161203e728

**Comment by lzoran** [comment]
Hi @proninyaroslav,

Thanks for the update!

Maybe I'm missing something, but it seems that the `intl_translation 0.17.10+1` still generates localization files where the analyzer for implicit-casts fails. 😕 

Example (generate localization files in your project via `intl_translation`):
```
flutter pub global activate intl_translation 0.17.10+1
flutter pub global run intl_translation:generate_from_arb lib\generated\l10n.dart lib\l10n\intl_en.arb
// check generated files...
``` 

Regarding the `intl_translation` version update, that is already in the plan and can be expected in one of the upcoming releases.

**Comment by aleksakrstic** [comment]
Lint errors are removed in version `1.9.0`
