### ISSUE TITLE
value of the [example_key] placeholder in message [name] must be a non-empty string

### ISSUE THREAD

**Issue by MauriiiM** [localizely/intl_utils#70]
First time creating a Git Issue myself, so sorry if I'm missing key information or I'm not following some outline (although I don't think there is one). Also I don't see an open issue for this already.

on 2.5.1 (it wasn't happening on my previous version 2.4.1)

`pub run intl_utils:generate`  will terminate early due to 
```
ERROR: Failed to generate localization files.
The 'example' value of the '[example_key]' placeholder in message '[name]' must be a non-empty string.
pub finished with exit code 2
```
Where the cause of the errors were [example_key] had an 'example_value' of integers or booleans (seemingly anything that isn't a string.)

**Comment by MauriiiM** [comment]
Note: if this change was on purpose and isn't a bug, I don't believe it shouldn't be the case for `plurals where the argument **needs** to be an integer

**Comment by lzoran** [comment]
Hi @MauriiiM,

Thanks for reporting this!

> on 2.5.1 (it wasn't happening on my previous version 2.4.1)

You are right. The version `intl_utils 2.5.1` now use more data from the metadata of string keys (placeholder type, format, etc.).

> ```ERROR: Failed to generate localization files.```

According to the error message, I would say you have an invalid value of the `example` attribute in the key metadata (if provided, it should be the non-empty string).

> Where the cause of the errors were [example_key] had an 'example_value' of integers or booleans (seemingly anything that isn't a string.)
>
> Note: if this change was on purpose and isn't an issue, I don't believe it shouldn't be the case for plurals where the argument needs to be an integer

Did you find some docs that allow other values (integers, booleans, etc.) for the `example` attribute in ARB files?

**Comment by MauriiiM** [comment]
*I corrected a double negative I had in my previous comment*


> According to the error message, I would say you have an invalid value of the example attribute in the **key metadata** (if provided, it should be the non-empty string).

it's the **value** that it's requiring as a `String`, not the **key**

>Did you find some docs that allow other values (integers, booleans, etc.) for the example attribute in ARB files?

 I didn't look for any docs, but I'm going off of two things:
- dart `Intl` functions' (`message()`, `plural()`, `select()`) `example` argument being of type `Map<String, Object>` and not of type `Map<String, String>`
- previous implementation of `intl_utils` would allow this, so I thought this to be a breaking issue. (I would assume this  is fundamental and would've been there from the beginning)

But for `plural()` specifically, the first argument required is of type `num`, which also needs to be included in `example`, but because `example` takes a `Map<String, Object>`, one wouldn't change it to a string. So there's kinda a discrepancy with the main package this works with and just the underlying logic of `plural()` needing and being a `num` and not a `string`

**Comment by lzoran** [comment]
You are right @MauriiiM. 
The methods of the `intl` package (`Intl.message`, `Intl.plural`, ...) have the optional parameter `examples` of the type `Map<String, Object>?`. Therefore, it would make sense to support other types for the `example` values in the ARB files.
However, another question arises. How would you set an example of a `DateTime` placeholder?

Also, the ARB files are very similar to the JSON files, and as such, they don't have the same types of data as the Dart. So the easiest way to bridge these two type environments is through strings (correct me if I missed something).

> But for plural() specifically, the first argument required is of type num, which also needs to be included in example, but because example takes a Map<String, Object>, one wouldn't change it to a string. So there's kinda a discrepancy with the main package this works with and just the underlying logic of plural() needing and being a num and not a string

As I know, the `examples` is optional parameter not used at the runtime, but as additional data for translators - [docs](https://github.com/dart-lang/intl/blob/fee2c2d16999d2e211354ecd2179f012ae4f93bd/lib/intl.dart#L160).

The plural message example in ARB file:
```
  "stringKey": "{count, plural, one {{count} item} other {{count} items}}",
  "@stringKey": {
    "placeholders": {
      "count": {
        "type": "num",
        "example": "1"
      }
    }
  }
```

The generated method in `l10n.dart` file:
```
  /// `{count, plural, one {{count} item} other {{count} items}}`
  String stringKey(num count) {
    return Intl.plural(
      count,
      one: '$count item',
      other: '$count items',
      name: 'stringKey',
      desc: '',
      args: [count],
    );
  }
```

I don't see any issue here. The ARB file contains the `example` that translators can use, and generated code works fine. 
_*It would be nice if we could use Dart types in ARB files, but as explained above, that is not possible afaik._
