### ISSUE TITLE
format of api token in credential file

### ISSUE THREAD

**Issue by Miamoto-Musashi** [localizely/intl_utils#74]
how to configure api_token in credential file? it gves constatly error and tried several format, would be enough to write little bit better the documentation with a real example

```bash
Unhandled exception:
type 'String' is not a subtype of type 'int' of 'index'
#0      new CredentialsConfig (package:intl_utils/src/config/credentials_config.dart:17:32)
#1      main (file:///Users/mac/progetti/flutter/.pub-cache/hosted/pub.dartlang.org/intl_utils-2.6.0/bin/localizely_upload_main.dart:29:29)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
pub finished with exit code 255```

my file format in `.localizely/credentials.yaml` is:
`api_token:xxxxxx`

**Comment by aleksakrstic** [comment]
Hi @Miamoto-Musashi
You need to add a whitespace after the `:` character in your `credentials.yaml` file.
So it should look like:

    api_token: xxxxxx

Thanks for reporting this, it seems a real example in the documentation could really help with this.

**Comment by Miamoto-Musashi** [comment]
would be nice to have this working example on the documentation

**Comment by lzoran** [comment]
Thanks for the feedback!
The `intl_utils 2.6.1` now has a more meaningful error message in case of wrongly formatted `credentials.yaml` file and an example.
