### ISSUE TITLE
Update intl dependency to 0.18.0

### ISSUE THREAD

**Issue by slavap** [localizely/intl_utils#96]
ecause no versions of intl_utils match >2.8.1 <3.0.0 and intl_utils 2.8.1 depends on intl ^0.17.0, intl_utils ^2.8.1 requires intl ^0.17.0.
So, because swtouch depends on both intl ^0.18.0 and intl_utils ^2.8.1, version solving failed.

**Comment by orestesgaolin** [comment]
Related to #98

**Comment by lzoran** [comment]
This should be fixed with the `intl_utils 2.8.2`.

Closing this issue as resolved.
